### ISSUE TITLE
module.js:487  Appimage

### ISSUE THREAD

**Issue by irrianlo** [Xzandro/sw-exporter#163]
Hello Im ussining linux.Appimage and when i launch via terminal it throws the following

****module.js:487
    throw err;
    ^
Error: Cannot find module '/tmp/.mount_SummonC03Kl5/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3****

**Comment by Xzandro** [comment]
See #157 Uploaded a new release package.
