### ISSUE TITLE
[BUG] Should ignore .DS_Store file in plugin directories

### ISSUE THREAD

**Issue by deirdresm** [Xzandro/sw-exporter#345]
**Describe the bug**
Failure upon launch that prevents loading plugins or operation.

**To Reproduce**
1. Have a Mac
2. Navigate to the user plugin directory using Finder. An invisible .DS_Store file will automagically be created (not something the user has control over).
3. Try launching sw-exporter. Boom.

Uncaught Exception:
/Users/deirdre/Desktop/Summoners War Exporter Files/plugins/.DS_Store:1

SyntaxError: Invalid or unexpected token
at Module._compile (internal/modules/cjs/loader.js:896:18)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
at Module.load (internal/modules/cjs/loader.js:816:32)
at Module._load (internal/modules/cjs/loader.js:728:14)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717:26)
at Module.require (internal/modules/cjs/loader.js:853:19)
at require (internal/modules/cjs/helpers.js:74:18)
at /Applications/Summoners War Exporter.app/Contents/Resources/app.asar/app/main.js:139:20
at Array.forEach (<anonymous>)

**Expected behavior**
Ignore the file .DS_Store as it is not a plugin.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 11.0.1 (though it has created this file in all MacOS versions, I just hadn't opened the plugin directory in Finder before)

**Smartphone (please complete the following information):**
 - Device: iPad Mini
 - OS: iOS 14.1

**Additional context**
This isn't OS version specific; MacOS has created this file for ages; it stores metadata about what the view layout for that directory is.

**Comment by Xzandro** [comment]
Should be fixed in the new commit. Feel free to let me know if it's working since I dont use MacOS.
