### ISSUE TITLE
SWexport error run on ARM64

### ISSUE THREAD

**Issue by uncompleted** [Xzandro/sw-exporter#483]
**Describe the bug**

I checkout the previous report #162, it's all related to the module: ./binaries/key-linux-arm64

- [Error message]:

chris@raspberrypi:~/Downloads/sw-exporter-master $ npm start

> sw-exporter@0.0.52 start
> electron .

App threw an error during load
Error: Cannot find module **'./binaries/key-linux-arm64'**
Require stack:
- /home/chris/Downloads/sw-exporter-master/app/proxy/smon_decryptor.js
- /home/chris/Downloads/sw-exporter-master/app/proxy/SWProxy.js
- /home/chris/Downloads/sw-exporter-master/app/main.js
- /home/chris/Downloads/sw-exporter-master/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:934:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:779:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/chris/Downloads/sw-exporter-master/app/proxy/smon_decryptor.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './binaries/key-linux-arm64'
Require stack:
- /home/chris/Downloads/sw-exporter-master/app/proxy/smon_decryptor.js
- /home/chris/Downloads/sw-exporter-master/app/proxy/SWProxy.js
- /home/chris/Downloads/sw-exporter-master/app/main.js
- /home/chris/Downloads/sw-exporter-master/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:934:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:779:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/chris/Downloads/sw-exporter-master/app/proxy/smon_decryptor.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)

- [Environment]:
chris@raspberrypi:~/Downloads/sw-exporter-master $ uname -a
Linux raspberrypi 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux

**Comment by Xzandro** [comment]
As long as github does not provide arm64 runners, I do not plan to provide it, sicne it would be quite a hassle to be honest. I personally do not have any device that runs arm64. https://github.com/actions/runner-images/issues/5631

Technically this is also a duplicate issue, but not sure which one I should close.

**Comment by Zgrill** [comment]
@Xzandro how do you generate or where did you obtain the `key-${process.platform}-${process.arch}.node` binary files? I am working from an Apple Silicon mac; couldn't get running with `arch -x86_64` to work. Happy to try and create/obtain the `key-darwin-arm64` file myself, but I don't know where they come from and Google has turned up nothing useful thusfar.

**Comment by eltranox** [comment]
@Xzandro Is it possible to get mac arm64 builds in the near future? Action runner images for Mac and arm64 exist like `macos-latest`.
See https://github.com/actions/runner-images

Apple also wants to stop support for x86/amd64 Mac applications (https://support.apple.com/en-us/102527). Therefore without native Mac arm builds the exporter might stop working in later Mac releases.

If there is any testing needed I will offer my help.
Sadly like @Zgrill mentioned without the matching `key` binary its not possible to create a working pr (see https://github.com/Xzandro/sw-exporter/issues/391).

It would be great if we could get that support! Thanks in advance!
